import fonts from "foundation/assets/fonts";

export const textVariants = {
  h1: {
    // fontFamily: fonts.LatoBold,
    fontSize: 26,
    lineHeight: 36,
    letterSpacing: 0,
    color: 'typography',
  },
  h2: {
    // fontFamily: fonts.LatoBold,
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0,
    color: 'typography',
  },
  h3: {
    // fontFamily: fonts.LatoBold,
    fontSize: 16,
    lineHeight: 26,
    letterSpacing: 0,
    color: 'typography',
  },
  h4Black: {
    // fontFamily: fonts.LatoBlack,
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: 0,
    color: 'typography',
  },
  h4Bold: {
    // fontFamily: fonts.LatoBold,
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: 0,
    color: 'typography',
  },
  h4: {
    // fontFamily: fonts.LatoBold,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
    color: 'typography',
  },
  h5: {
    // fontFamily: fonts.LatoBold,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0,
    color: 'typography',
  },
  h6: {
    // fontFamily: fonts.LatoBold,
    fontSize: 10,
    lineHeight: 14,
    letterSpacing: 0,
    color: 'typography',
  },
  body1Serif: {
    // fontFamily: fonts.LatoRegular,
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0,
    color: 'typography',
  },
  body1Sans: {
    fontFamily: fonts.OpensansRegular,
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0,
    color: 'typography',
  },
  body2Serif: {
    // fontFamily: fonts.LatoRegular,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
    color: 'typography',
  },
  body2Sans: {
    // fontFamily: fonts.LatoRegular,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
    color: 'typography',
  },
  body3: {
    // fontFamily: fonts.LatoRegular,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0,
    color: 'typography',
  },
  body3Sans: {
    // fontFamily: fonts.LatoRegular,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0,
    color: 'typography',
  },
  label1: {
    // fontFamily: fonts.LatoRegular,
    fontSize: 14,
    lineHeight: 19,
    letterSpacing: 0,
    color: 'typography',
  },
  inputRegular: {
    // fontFamily: fonts.LatoRegular,
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: 0,
    color: 'typography',
  },
  inputBold: {
    // fontFamily: fonts.LatoBold,
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: 0,
    color: 'typography',
  },
  regular_button: {
    color: 'white',
    fontSize: 16,
    lineHeight: 22,
    // fontFamily: fonts.LatoRegular,
    textTransform: 'uppercase',
  },
} as const;

export type TextVariant = keyof typeof textVariants;
