const IMAGES = {
  splash_logo: require('./SplashLogo.png'),
  homeIcon: require('./home.png'),
  homeFillIcon: require('./home_green.png'),
  searchIcon: require('./search.png'),
  searchFillIcon: require('./search_green.png'),
  journalIcon: require('./Collanote.png'),
  journalFillIcon: require('./Collanote_green.png'),
  profileIcon: require('./profile.png'),
  profileFillIcon: require('./profile_green.png'),
  closeIcon: require('./close.png'),
  mailIcon: require('./email.png'),
  userIcon: require('./user.png'),
  logoWhite: require('./logo_white.png'),
  camera: require('./camera.png'),
  goalIcon: require('./goalIcon.png'),
  highFive: require('./highFive.png'),
  wiseMind: require('./WiseMind.png'),
  pencil: require('./pencil.png'),
  lock: require('./Lock.png'),
  bulletArrow: require('./bulletArrow.png'),
  shortRightArrow: require('./shortRightArrow.png'),
  notificationStack: require('./notifications-stacked.png'),
  Library: require('./Library.png'),
  LibraryFilIcon: require('./Library_green.png'),
  startJournalIcon: require('./journal.png'),
  Resources: require('./resources_light_gray.png'),
  ResourcesFilIcon: require('./green_resources.png'),
  WhiteProfilePlaceholder: require('./white_profile.png'),
  GreenTick: require('./greencheck.png'),
  WhitePencil: require('./whitepencil.png'),
  WhiteCircle: require('./whitecircle.png'),
};

export default IMAGES;
